name: Feature Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  featureTests:
    name: FeatureTests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        mongodb-version: ['6.0', '7.0', '8.0']

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Install dependencies
        run: npm install

      - name: Setup env
        run: cp ./env-cucumber.json .env-cucumber.json

      - name: Run Cucumber Tests
        run: npm run test:feature
